version: "3.8"

services:
  application:
    build:
      context: .
      dockerfile: infrastructure/application.Dockerfile
    container_name: scrapbook
    env_file:
      - .env
    networks:
      - scrapbook
    ports:
      - 3000:3000
    volumes:
      - ./:/app:cached
    entrypoint: [ "npm", "run", "dev" ]

  mysql:
    image: library/mysql:8
    container_name: scrapbook_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scrapbook
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - scrapbook
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql:delegated

  redis:
    image: library/redis:6
    command: redis-server
    container_name: scrapbook_redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - scrapbook
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis:/data:delegated

networks:
  scrapbook:
