version: "3.8"

services:
  mysql:
    image: library/mysql:8
    container_name: scrapbook_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scrapbook
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - scrapbook
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql:delegated

  redis:
    image: library/redis:6
    command: redis-server
    container_name: scrapbook_redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - scrapbook
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis:/data:delegated

networks:
  scrapbook:
