version: "3.8"

services:
  redis:
    image: library/redis:6
    command: redis-server
    container_name: scrapbook_redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - scrapbook
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis:/data

networks:
  scrapbook:
